import torch
import time
from torch_cluster import radius_graph
from torch_scatter import scatter_add, scatter_min

def run_clue_pytorch(points, energy, dc=2.0, rhoc=4.0, dm=4.0, max_num_neighbors=200):
    """
    Optimized CLUE Algorithm.
    """
    # Ensure inputs are on the correct device and contiguous
    if not points.is_cuda and torch.cuda.is_available():
        points = points.cuda()
        energy = energy.cuda()
        
    device = points.device
    N = points.size(0)
    
    # Pre-compute squared radii to avoid sqrt() operations later
    dc2 = dc * dc
    dm2 = dm * dm
    max_r = max(dc, dm)

    # --- Step 1: Build ONE Graph for both Rho and Delta ---
    # We query with the largest required radius (usually dm).
    # We increase max_num_neighbors slightly to ensure we don't miss higher density points.
    edge_index = radius_graph(points, r=max_r, max_num_neighbors=max_num_neighbors, loop=True)
    row, col = edge_index

    # Compute Squared Euclidean Distance for ALL edges at once
    # (Faster than torch.norm)
    diff = points[row] - points[col]
    dist_sq = (diff * diff).sum(dim=1)

    # --- Step 2: Calculate Local Density (Rho) ---
    # Filter edges that are within dc (dist^2 <= dc^2)
    rho_mask = dist_sq <= dc2
    
    # Sum energy of neighbors
    # row is the target point index, col is the neighbor index
    rho = scatter_add(energy[col[rho_mask]], row[rho_mask], dim=0, dim_size=N)

    # --- Step 3: Nearest Higher Density (Delta) ---
    # We need edges where:
    # 1. Neighbor (col) has higher density than self (row)
    # 2. OR densities are equal but neighbor index is higher (tie-breaker)
    # 3. AND distance is within dm (dist^2 <= dm^2)
    
    rho_row = rho[row]
    rho_col = rho[col]
    
    # Combine logic into one boolean mask
    # Note: We perform the density check on ALL edges generated by max_r.
    # If dc < dm, some edges valid for delta were not used for rho, which is correct.
    is_higher = (rho_col > rho_row) | ((rho_col == rho_row) & (col > row))
    
    # If dm != max_r (unlikely, but safe), mask by distance too
    if dm < max_r:
        is_higher &= (dist_sq <= dm2)

    # Filter distances and indices
    valid_dists_sq = dist_sq[is_higher]
    valid_rows = row[is_higher]
    
    # Find minimum squared distance to a higher density neighbor
    # Initialize with infinity
    delta_sq = torch.full((N,), float('inf'), device=device)
    
    # Update delta_sq in-place
    scatter_min(valid_dists_sq, valid_rows, out=delta_sq, dim=0, dim_size=N)
    
    # Now take the sqrt only for the valid deltas to get actual distance
    delta = delta_sq.sqrt()
    
    # --- Step 4: Identify Seeds ---
    is_seed = (rho > rhoc) & (delta > dm)
    
    return rho, delta, is_seed

